export const TYPE_BY_COLOR = {
  normal: { ko: '노말', en: 'normal', color: '#A8A77A' },
  fire: { ko: '불꽃', en: 'fire', color: '#EE8130' },
  water: { ko: '물', en: 'water', color: '#6390F0' },
  electric: { ko: '전기', en: 'electric', color: '#F7D02C' },
  grass: { ko: '풀', en: 'grass', color: '#7AC74C' },
  ice: { ko: '얼음', en: 'ice', color: '#96D9D6' },
  fighting: { ko: '격투', en: 'fighting', color: '#C22E28' },
  poison: { ko: '독', en: 'poison', color: '#A33EA1' },
  ground: { ko: '땅', en: 'ground', color: '#E2BF65' },
  flying: { ko: '비행', en: 'flying', color: '#A98FF3' },
  psychic: { ko: '에스퍼', en: 'psychic', color: '#F95587' },
  bug: { ko: '벌레', en: 'bug', color: '#A6B91A' },
  rock: { ko: '바위', en: 'rock', color: '#B6A136' },
  ghost: { ko: '고스트', en: 'ghost', color: '#735797' },
  dragon: { ko: '드래곤', en: 'dragon', color: '#6F35FC' },
  dark: { ko: '악', en: 'dark', color: '#705746' },
  steel: { ko: '강철', en: 'steel', color: '#B7B7CE' },
  fairy: { ko: '페어리', en: 'fairy', color: '#D685AD' },
};
