export const TYPE_BY_COLOR = {
  normal: { num: 1, ko: '노말', en: 'Normal', color: '#A8A77A' },
  fire: { num: 10, ko: '불꽃', en: 'Fire', color: '#EE8130' },
  water: { num: 11, ko: '물', en: 'Water', color: '#6390F0' },
  electric: { num: 13, ko: '전기', en: 'Electric', color: '#F7D02C' },
  grass: { num: 12, ko: '풀', en: 'Grass', color: '#7AC74C' },
  ice: { num: 15, ko: '얼음', en: 'Ice', color: '#96D9D6' },
  fighting: { num: 2, ko: '격투', en: 'Fighting', color: '#C22E28' },
  poison: { num: 4, ko: '독', en: 'Poison', color: '#A33EA1' },
  ground: { num: 5, ko: '땅', en: 'Ground', color: '#E2BF65' },
  flying: { num: 3, ko: '비행', en: 'Flying', color: '#A98FF3' },
  psychic: { num: 14, ko: '에스퍼', en: 'Psychic', color: '#F95587' },
  bug: { num: 7, ko: '벌레', en: 'Bug', color: '#A6B91A' },
  rock: { num: 6, ko: '바위', en: 'Rock', color: '#B6A136' },
  ghost: { num: 8, ko: '고스트', en: 'Ghost', color: '#735797' },
  dragon: { num: 16, ko: '드래곤', en: 'Dragon', color: '#6F35FC' },
  dark: { num: 17, ko: '악', en: 'Dark', color: '#705746' },
  steel: { num: 9, ko: '강철', en: 'Steel', color: '#B7B7CE' },
  fairy: { num: 18, ko: '페어리', en: 'Fairy', color: '#D685AD' },
};
